// Plinko paytables + geometry helpers.
//
// PLINKO_TABLES is generated by scripts/gen_plinko.mjs and is the SAME data
// embedded in supabase/migrations/0014_plinko.sql. The server is authoritative
// for the payout; the client uses these only to draw the bucket labels and to
// size the board. If you change one, regenerate and update BOTH.

export type PlinkoRisk = "low" | "medium" | "high";

export const PLINKO_RISKS: PlinkoRisk[] = ["low", "medium", "high"];
// Stake supports 8–16 rows.
export const PLINKO_ROWS = [8, 9, 10, 11, 12, 13, 14, 15, 16];
export const PLINKO_MIN_ROWS = 8;
export const PLINKO_MAX_ROWS = 16;

export const PLINKO_TABLES: Record<PlinkoRisk, Record<number, number[]>> = {
  low: {
    8: [3, 2, 1.3, 0.9, 0.6, 0.9, 1.3, 2, 3],
    9: [3.5, 2.3, 1.5, 1, 0.7, 0.7, 1, 1.5, 2.3, 3.5],
    10: [4.3, 2.8, 1.8, 1.2, 0.8, 0.5, 0.8, 1.2, 1.8, 2.8, 4.3],
    11: [5, 3.3, 2.2, 1.4, 0.9, 0.6, 0.6, 0.9, 1.4, 2.2, 3.3, 5],
    12: [6, 4, 2.6, 1.7, 1.1, 0.7, 0.5, 0.7, 1.1, 1.7, 2.6, 4, 6],
    13: [7.1, 4.7, 3.1, 2, 1.3, 0.9, 0.6, 0.6, 0.9, 1.3, 2, 3.1, 4.7, 7.1],
    14: [8.6, 5.6, 3.7, 2.4, 1.6, 1.1, 0.7, 0.5, 0.7, 1.1, 1.6, 2.4, 3.7, 5.6, 8.6],
    15: [10.1, 6.7, 4.4, 2.9, 1.9, 1.2, 0.8, 0.5, 0.5, 0.8, 1.2, 1.9, 2.9, 4.4, 6.7, 10.1],
    16: [12.2, 8, 5.3, 3.5, 2.3, 1.5, 1, 0.6, 0.4, 0.6, 1, 1.5, 2.3, 3.5, 5.3, 8, 12.2],
  },
  medium: {
    8: [6.2, 3, 1.5, 0.7, 0.3, 0.7, 1.5, 3, 6.2],
    9: [8, 3.9, 1.9, 0.9, 0.4, 0.4, 0.9, 1.9, 3.9, 8],
    10: [10.8, 5.2, 2.6, 1.2, 0.6, 0.3, 0.6, 1.2, 2.6, 5.2, 10.8],
    11: [14.1, 6.9, 3.3, 1.6, 0.8, 0.4, 0.4, 0.8, 1.6, 3.3, 6.9, 14.1],
    12: [19, 9.3, 4.5, 2.2, 1.1, 0.5, 0.3, 0.5, 1.1, 2.2, 4.5, 9.3, 19],
    13: [25.1, 12.2, 5.9, 2.9, 1.4, 0.7, 0.3, 0.3, 0.7, 1.4, 2.9, 5.9, 12.2, 25.1],
    14: [33.7, 16.4, 8, 3.9, 1.9, 0.9, 0.4, 0.2, 0.4, 0.9, 1.9, 3.9, 8, 16.4, 33.7],
    15: [44.6, 21.7, 10.6, 5.1, 2.5, 1.2, 0.6, 0.3, 0.3, 0.6, 1.2, 2.5, 5.1, 10.6, 21.7, 44.6],
    16: [60, 29.2, 14.2, 6.9, 3.4, 1.6, 0.8, 0.4, 0.2, 0.4, 0.8, 1.6, 3.4, 6.9, 14.2, 29.2, 60],
  },
  high: {
    8: [12.1, 4.2, 1.5, 0.5, 0.2, 0.5, 1.5, 4.2, 12.1],
    9: [17.5, 6.1, 2.1, 0.7, 0.3, 0.3, 0.7, 2.1, 6.1, 17.5],
    10: [25.9, 9.1, 3.2, 1.1, 0.4, 0.1, 0.4, 1.1, 3.2, 9.1, 25.9],
    11: [37.8, 13.2, 4.6, 1.6, 0.6, 0.2, 0.2, 0.6, 1.6, 4.6, 13.2, 37.8],
    12: [56, 19.6, 6.9, 2.4, 0.8, 0.3, 0.1, 0.3, 0.8, 2.4, 6.9, 19.6, 56],
    13: [81.9, 28.7, 10, 3.5, 1.2, 0.4, 0.2, 0.2, 0.4, 1.2, 3.5, 10, 28.7, 81.9],
    14: [121, 42.5, 14.9, 5.2, 1.8, 0.6, 0.2, 0.1, 0.2, 0.6, 1.8, 5.2, 14.9, 42.5, 121],
    15: [178, 62.4, 21.8, 7.6, 2.7, 0.9, 0.3, 0.1, 0.1, 0.3, 0.9, 2.7, 7.6, 21.8, 62.4, 178],
    16: [264, 92.5, 32.4, 11.3, 4, 1.4, 0.5, 0.2, 0.1, 0.2, 0.5, 1.4, 4, 11.3, 32.4, 92.5, 264],
  },
};

export function plinkoMultipliers(risk: PlinkoRisk, rows: number): number[] {
  return PLINKO_TABLES[risk][rows] ?? PLINKO_TABLES[risk][PLINKO_MAX_ROWS];
}

// Bucket colour: hot at the high-paying edges, cool toward the centre — the
// classic Stake red→amber→yellow gradient. `k` is the bucket index, `n` rows.
export function bucketColor(k: number, n: number): string {
  const t = Math.abs(k - n / 2) / (n / 2); // 0 centre … 1 edge
  // interpolate yellow (centre) → amber → red (edge)
  const stops = [
    [255, 210, 64], // #ffd240 centre
    [255, 145, 40], // #ff9128
    [244, 63, 94], // #f43f5e edge
  ];
  const seg = t >= 0.5 ? 1 : 0;
  const local = t >= 0.5 ? (t - 0.5) * 2 : t * 2;
  const a = stops[seg];
  const b = stops[seg + 1];
  const c = a.map((v, i) => Math.round(v + (b[i] - v) * local));
  return `rgb(${c[0]}, ${c[1]}, ${c[2]})`;
}
