-- ============================================================================
-- EBHS Polymarket — migration 0014: PLINKO
--
-- Adds a Stake-style Plinko game to the casino. A ball drops through `rows`
-- pegs (8–16); at each peg it goes left or right 50/50, landing in one of
-- rows+1 buckets. The bucket's multiplier (from the paytable below) is paid.
--
-- Same design as the rest of the casino (migration 0009): all randomness +
-- payout happen here, server-side, behind app.privileged. The path is returned
-- so the client can animate the exact drop that produced the result.
--
-- The paytables are generated by scripts/gen_plinko.mjs and are byte-identical
-- to PLINKO_TABLES in src/lib/casino/plinko.ts (verified house edge 1–7%,
-- capped at 1000×). Run on top of 0001–0013. Re-runnable.
-- ============================================================================

create or replace function public.casino_plinko(p_bet numeric, p_rows int, p_risk text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_path jsonb := '[]'::jsonb;
  v_bucket int := 0;
  v_mult numeric;
  v_payout numeric := 0;
  v_new_balance numeric;
  i int;
  v_tables jsonb := '{"low":{"8":[3,2,1.3,0.9,0.6,0.9,1.3,2,3],"9":[3.5,2.3,1.5,1,0.7,0.7,1,1.5,2.3,3.5],"10":[4.3,2.8,1.8,1.2,0.8,0.5,0.8,1.2,1.8,2.8,4.3],"11":[5,3.3,2.2,1.4,0.9,0.6,0.6,0.9,1.4,2.2,3.3,5],"12":[6,4,2.6,1.7,1.1,0.7,0.5,0.7,1.1,1.7,2.6,4,6],"13":[7.1,4.7,3.1,2,1.3,0.9,0.6,0.6,0.9,1.3,2,3.1,4.7,7.1],"14":[8.6,5.6,3.7,2.4,1.6,1.1,0.7,0.5,0.7,1.1,1.6,2.4,3.7,5.6,8.6],"15":[10.1,6.7,4.4,2.9,1.9,1.2,0.8,0.5,0.5,0.8,1.2,1.9,2.9,4.4,6.7,10.1],"16":[12.2,8,5.3,3.5,2.3,1.5,1,0.6,0.4,0.6,1,1.5,2.3,3.5,5.3,8,12.2]},"medium":{"8":[6.2,3,1.5,0.7,0.3,0.7,1.5,3,6.2],"9":[8,3.9,1.9,0.9,0.4,0.4,0.9,1.9,3.9,8],"10":[10.8,5.2,2.6,1.2,0.6,0.3,0.6,1.2,2.6,5.2,10.8],"11":[14.1,6.9,3.3,1.6,0.8,0.4,0.4,0.8,1.6,3.3,6.9,14.1],"12":[19,9.3,4.5,2.2,1.1,0.5,0.3,0.5,1.1,2.2,4.5,9.3,19],"13":[25.1,12.2,5.9,2.9,1.4,0.7,0.3,0.3,0.7,1.4,2.9,5.9,12.2,25.1],"14":[33.7,16.4,8,3.9,1.9,0.9,0.4,0.2,0.4,0.9,1.9,3.9,8,16.4,33.7],"15":[44.6,21.7,10.6,5.1,2.5,1.2,0.6,0.3,0.3,0.6,1.2,2.5,5.1,10.6,21.7,44.6],"16":[60,29.2,14.2,6.9,3.4,1.6,0.8,0.4,0.2,0.4,0.8,1.6,3.4,6.9,14.2,29.2,60]},"high":{"8":[12.1,4.2,1.5,0.5,0.2,0.5,1.5,4.2,12.1],"9":[17.5,6.1,2.1,0.7,0.3,0.3,0.7,2.1,6.1,17.5],"10":[25.9,9.1,3.2,1.1,0.4,0.1,0.4,1.1,3.2,9.1,25.9],"11":[37.8,13.2,4.6,1.6,0.6,0.2,0.2,0.6,1.6,4.6,13.2,37.8],"12":[56,19.6,6.9,2.4,0.8,0.3,0.1,0.3,0.8,2.4,6.9,19.6,56],"13":[81.9,28.7,10,3.5,1.2,0.4,0.2,0.2,0.4,1.2,3.5,10,28.7,81.9],"14":[121,42.5,14.9,5.2,1.8,0.6,0.2,0.1,0.2,0.6,1.8,5.2,14.9,42.5,121],"15":[178,62.4,21.8,7.6,2.7,0.9,0.3,0.1,0.1,0.3,0.9,2.7,7.6,21.8,62.4,178],"16":[264,92.5,32.4,11.3,4,1.4,0.5,0.2,0.1,0.2,0.5,1.4,4,11.3,32.4,92.5,264]}}'::jsonb;
begin
  if v_uid is null then raise exception 'You must be logged in.'; end if;
  if p_bet is null or p_bet <= 0 then raise exception 'Bet must be greater than zero.'; end if;
  if p_bet > 1000000 then raise exception 'Bet is too large.'; end if;
  if p_rows is null or p_rows < 8 or p_rows > 16 then raise exception 'Rows must be between 8 and 16.'; end if;
  if p_risk not in ('low', 'medium', 'high') then raise exception 'Risk must be low, medium or high.'; end if;

  perform set_config('app.privileged', 'on', true);
  update public.profiles set balance = balance - p_bet
    where id = v_uid and balance >= p_bet;
  if not found then raise exception 'Insufficient balance.'; end if;

  -- Drop the ball: each peg is a fair coin; bucket = number of right-moves.
  for i in 1 .. p_rows loop
    if random() < 0.5 then
      v_path := v_path || '0'::jsonb;            -- left
    else
      v_path := v_path || '1'::jsonb;            -- right
      v_bucket := v_bucket + 1;
    end if;
  end loop;

  v_mult := coalesce((v_tables -> p_risk -> p_rows::text -> v_bucket)::numeric, 0);
  if v_mult > 1000 then v_mult := 1000; end if;   -- max-win safeguard

  if v_mult > 0 then
    v_payout := round(p_bet * v_mult, 2);
    update public.profiles set balance = balance + v_payout where id = v_uid
      returning balance into v_new_balance;
  else
    select balance into v_new_balance from public.profiles where id = v_uid;
  end if;

  insert into public.casino_bets (user_id, game, bet, payout, multiplier, result)
  values (v_uid, 'plinko', p_bet, v_payout, v_mult,
          jsonb_build_object('rows', p_rows, 'risk', p_risk, 'bucket', v_bucket, 'path', v_path));

  return json_build_object(
    'rows', p_rows, 'risk', p_risk, 'bucket', v_bucket, 'path', v_path,
    'multiplier', v_mult, 'payout', v_payout, 'win', v_mult >= 1, 'new_balance', v_new_balance
  );
end;
$$;

grant execute on function public.casino_plinko(numeric, int, text) to authenticated;

notify pgrst, 'reload schema';

-- ============================================================================
-- End of migration 0014.
-- ============================================================================
